services:
  postgres:
    image: postgres:17
    container_name: expense-tracker-postgres
    environment:
      POSTGRES_DB: expensetracker
      POSTGRES_USER: expensetracker
      POSTGRES_PASSWORD: expensetracker123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/posgresql/data

volumes:
  postgres_data: