spring:
  application:
    name: expensetracker

  datasource:
    url: jdbc:postgresql://localhost:5432/expensetracker
    username: expensetracker
    password: expensetracker123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true

  jwt:
    secret: my-super-secret-development-key-123456
    expiration: 3600000